apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: primeiro-pod

# put the load balancer in a cloud platform to make the cluster open
# to the public with all the aplications we did
# They are utilize automatic the balancers from the cloud providers
# so there is no need to further configuration